"""test_reporting.py — the canonical report model and both renderers (Kati).

Scope: `pipeline/reporting.py` in isolation — no UI, no AppTest. Three
things are pinned:

  * `build_report` is a PURE, DETERMINISTIC reduction of an ACCEPTED state:
    every value it produces traces back to a field already on the run, a
    FAIL verdict and an open finding survive acceptance unchanged, and
    nothing is generated by an LLM;
  * `render_markdown` and `render_pdf` read ONLY `ReportData` and agree on
    what exists — see the "canonical model" test class;
  * `generate_reports` writes atomically, fails per-format independently,
    and never leaves a partial file or a stray temp file behind.

No network, no LLM: `_rich_accepted_state` is hand-built (same style as
test_sign_off.py's fixtures), and the two agent responses it needs (via
`test_user_feedback._done_passed_state`) are already canned. Every test that
touches disk overrides `AI_ARCHITECT_RUNS_DIR` itself (via `monkeypatch`), on
top of the session-wide redirect in conftest.py, so nothing here ever writes
into a real run history.
"""
from __future__ import annotations

from io import BytesIO
from pathlib import Path

import pytest
from pypdf import PdfReader

import test_user_feedback as tuf
from pipeline import reporting, sign_off
from pipeline.state import (
    ArchitectState,
    DecisionTopic,
    KBChunk,
    MigrationStep,
    ReviewIssue,
    Stage,
)

LONG_TEXT = (
    "This component absorbs load spikes and decouples producers from "
    "consumers so that a flash sale never doubles-books inventory. " * 40
)


# ══════════════════════════════════════════════════════════════════════════
# Builders
# ══════════════════════════════════════════════════════════════════════════
def _rich_done_state() -> ArchitectState:
    """A DONE run carrying one of everything a report can show: a curated
    evidence item AND a web-fallback one, a decision topic WITH evidence and
    one WITHOUT (a verified gap), an ADR with alternatives/consequences, a
    migration step, and a FAILED review with one deterministic and one
    LLM-owned open finding. Realistic Unicode throughout (em dash, accented
    Latin, a checkmark, an arrow) — never CJK, which is not this project's
    content and not covered by the vendored font.
    """
    state = tuf._done_passed_state()
    state.context_record.business_goal = (
        "Sell sneakers online — profitably, at scale (café, naïve résumé)."
    )
    state.context_record.users = ["Shoppers", "Ops team"]
    state.context_record.non_functional_requirements = ["99.9% availability"]
    state.context_record.compliance_requirements = ["GDPR"]
    state.context_record.existing_systems = ["Legacy monolith on EC2"]
    state.context_record.assumptions = ["Traffic peaks 5x on sale days"]
    state.context_record.open_questions = ["Should we support multi-region?"]

    state.decision_topics = [
        DecisionTopic(
            id="TOPIC-1", topic="Event backbone choice",
            query="kafka vs sqs", evidence_ids=["KB-E001"],
        ),
        DecisionTopic(
            id="TOPIC-2", topic="Data consistency strategy",
            query="saga vs 2pc", evidence_ids=[],
        ),
    ]
    state.retrieved_knowledge = [
        KBChunk(
            content="Use event sourcing for auditability and replay.",
            source="Fowler, Enterprise Patterns", page=42, box=1,
            evidence_id="KB-E001",
        ),
        KBChunk(
            content="General web result about microservices trends.",
            source="https://example.com/microservices", page=0, box=3,
            evidence_id="",
        ),
    ]

    state.adrs[0].related_decision_topic_ids = ["TOPIC-1"]
    state.adrs[0].evidence_ids = ["KB-E001"]
    state.adrs[0].context = "We need durable ordering — checkmark: ✓ arrow: →."
    state.adrs[0].rationale = "Kafka gives partition-level ordering and replay."
    state.adrs[0].alternatives_considered = ["Amazon SQS", "RabbitMQ"]
    state.adrs[0].positive_consequences = ["Replayable event log"]
    state.adrs[0].negative_consequences = ["Operational overhead of running Kafka"]

    state.blueprint.data_flows = [
        "Order Service -> Kafka Event Bus: order.created event",
    ]
    state.blueprint.migration_steps = [
        MigrationStep(
            title="Introduce the order event seam",
            objective="Decouple checkout from inventory.",
            changes=["Add Kafka topic order.created"],
            coexistence_or_data_strategy="Monolith and new service both write during transition.",
            exit_condition="100% of orders emit the event with zero data loss.",
        )
    ]
    state.components[0].technology_choices = ["Apache Kafka", "AWS MSK"]

    state.review.issues = [
        ReviewIssue(
            id="DET-1", severity="medium", category="traceability",
            finding="One component has no related ADR.",
            evidence="Kafka Event Bus", suggested_fix="Add related_adr_ids.",
        ),
        ReviewIssue(
            id="LLM-1", severity="high", category="grounding",
            finding="Repo grounding insufficient.",
            evidence="No repo evidence cited.", suggested_fix="Cite specific files.",
        ),
    ]
    state.review.overall_status = "fail"
    state.stopped_on_cap = True
    state.refine_iterations = 3
    state.selected_round = 2
    return state


def _rich_accepted_state(note: str = "Accepted for pilot, tracked in JIRA-123") -> ArchitectState:
    state = _rich_done_state()
    sign_off.accept_design(state, note=note)
    return state


def _extract_pdf_text(pdf_bytes: bytes) -> str:
    reader = PdfReader(BytesIO(pdf_bytes))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


# ══════════════════════════════════════════════════════════════════════════
# 1. The canonical report model
# ══════════════════════════════════════════════════════════════════════════
def test_build_report_requires_an_accepted_run():
    """A draft must never impersonate a sign-off — see the module docstring."""
    state = _rich_done_state()
    assert state.stage is Stage.DONE
    with pytest.raises(reporting.ReportError, match="ACCEPTED"):
        reporting.build_report(state)


def test_build_report_is_deterministic():
    state = _rich_accepted_state()
    assert reporting.build_report(state) == reporting.build_report(state)


def test_requirements_and_constraints_preserved_exactly():
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    assert report.context_record == state.context_record


def test_components_data_flows_adrs_migration_steps_preserved():
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    assert report.components == state.components
    assert report.adrs == state.adrs
    assert report.blueprint.data_flows == state.blueprint.data_flows
    assert report.blueprint.migration_steps == state.blueprint.migration_steps
    assert report.features == state.features


def test_evidence_ids_and_provenance_preserved():
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    curated = next(e for e in report.evidence if e.is_curated)
    web = next(e for e in report.evidence if not e.is_curated)
    assert curated.evidence_id == "KB-E001"
    assert curated.source == "Fowler, Enterprise Patterns"
    assert curated.page == 42
    assert web.evidence_id == ""
    assert web.source == "https://example.com/microservices"


def test_reviewer_verdict_and_findings_preserved():
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    assert report.review == state.review
    origins = {f.id: f.origin for f in report.findings}
    assert origins == {"DET-1": "deterministic", "LLM-1": "llm"}


def test_finding_origin_falls_back_to_unknown_for_an_unrecognised_prefix():
    state = _rich_done_state()
    state.review.issues = [
        ReviewIssue(id="OTHER-1", severity="low", finding="Something else.")
    ]
    sign_off.accept_design(state)
    report = reporting.build_report(state)
    assert report.findings[0].origin == "unknown"


def test_unresolved_findings_and_kb_gaps_are_not_hidden_by_acceptance():
    """Acceptance means a human took the design — not that the record forgets
    what it was taken despite (see pipeline/sign_off.py)."""
    state = _rich_accepted_state()
    report = reporting.build_report(state)

    assert {f.id for f in report.findings} == {"DET-1", "LLM-1"}
    assert [t.id for t in report.decision_topics if t.has_gap] == ["TOPIC-2"]
    assert any("TOPIC-2" in item for item in report.limitations.evidence_gaps)
    assert any("LLM-1" in item for item in report.limitations.unresolved_high)
    assert any("DET-1" in item for item in report.limitations.unresolved_medium)
    assert report.waiver is not None
    assert set(report.waiver.finding_ids) == {"DET-1", "LLM-1"}


def test_traceability_maps_are_exact_id_matches_only():
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    trace = report.traceability
    assert trace.feature_to_adrs["FEAT-001"] == ["ADR-001"]
    assert trace.feature_to_components["FEAT-001"] == ["COMP-001"]
    assert trace.decision_topic_to_adrs["TOPIC-1"] == ["ADR-001"]
    assert trace.decision_topic_to_adrs["TOPIC-2"] == []
    assert trace.adr_to_evidence["ADR-001"] == ["KB-E001"]


def test_executive_summary_prefers_the_blueprint_stakeholder_view():
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    assert report.executive_summary == state.blueprint.stakeholder_view.strip()


def test_executive_summary_falls_back_to_a_deterministic_combination():
    state = _rich_done_state()
    state.blueprint.stakeholder_view = ""
    sign_off.accept_design(state)
    report = reporting.build_report(state)

    assert state.context_record.business_goal.strip() in report.executive_summary
    assert state.context_record.problem_statement.strip() in report.executive_summary
    assert "FAIL" in report.executive_summary


def test_no_fabricated_content_beyond_the_executive_summary_combination():
    """Every OTHER field on `ReportData` is a passthrough or a deterministic
    ID-keyed map — never a new sentence the state itself does not contain."""
    state = _rich_accepted_state()
    report = reporting.build_report(state)
    assert report.blueprint == state.blueprint
    assert report.review == state.review
    assert report.context_record == state.context_record


# ══════════════════════════════════════════════════════════════════════════
# 2. Markdown renderer
# ══════════════════════════════════════════════════════════════════════════
def test_markdown_rendering_is_deterministic():
    report = reporting.build_report(_rich_accepted_state())
    assert reporting.render_markdown(report) == reporting.render_markdown(report)


def test_markdown_contains_every_required_section():
    report = reporting.build_report(_rich_accepted_state())
    md = reporting.render_markdown(report)
    for heading in (
        "# AI-Architect Architecture Report",
        "## Executive Summary",
        "## Requirements & Constraints",
        "## Recommended Architecture",
        "## Data Flows",
        "## Architecture Decision Records",
        "## Migration Plan",
        "## Evidence / Literature",
        "## Validation & Reviewer Findings",
        "## Traceability",
        "## Limitations / Open Items",
    ):
        assert heading in md, heading


def test_markdown_retains_stable_ids():
    report = reporting.build_report(_rich_accepted_state())
    md = reporting.render_markdown(report)
    for stable_id in ("ADR-001", "KB-E001", "FEAT-001", "COMP-001", "TOPIC-1", "TOPIC-2"):
        assert stable_id in md, stable_id


def test_markdown_has_no_absolute_developer_paths():
    report = reporting.build_report(_rich_accepted_state())
    md = reporting.render_markdown(report)
    assert str(Path.cwd()) not in md
    assert "C:\\Users" not in md
    assert "/home/" not in md


def test_markdown_handles_empty_optional_fields_cleanly():
    """A minimal accepted run (no blueprint, no ADRs, no review) renders with
    every data-dependent section simply absent, never as an empty stub."""
    state = tuf._seed_designable_state()
    state.stage = Stage.DONE
    sign_off.accept_design(state)
    report = reporting.build_report(state)
    md = reporting.render_markdown(report)

    assert "## Recommended Architecture" not in md
    assert "## Architecture Decision Records" not in md
    assert "## Migration Plan" not in md
    assert "## Evidence / Literature" not in md
    assert "## Validation & Reviewer Findings" not in md
    assert "No unresolved items are recorded on this run." in md


def test_fail_verdict_and_open_findings_remain_visible_after_acceptance():
    report = reporting.build_report(_rich_accepted_state())
    md = reporting.render_markdown(report)
    assert "FAIL" in md
    assert "DET-1" in md and "LLM-1" in md
    assert "Waiver:" in md


# ══════════════════════════════════════════════════════════════════════════
# 3. PDF renderer
# ══════════════════════════════════════════════════════════════════════════
def test_pdf_has_a_valid_signature_and_trailer():
    pdf_bytes = reporting.render_pdf(reporting.build_report(_rich_accepted_state()))
    assert pdf_bytes[:5] == b"%PDF-"
    assert b"%%EOF" in pdf_bytes[-2048:]
    assert len(pdf_bytes) > 3000


def test_pdf_is_multi_page_and_non_empty():
    pdf_bytes = reporting.render_pdf(reporting.build_report(_rich_accepted_state()))
    reader = PdfReader(BytesIO(pdf_bytes))
    assert len(reader.pages) >= 2


def test_pdf_core_text_can_be_extracted_and_read_back():
    pdf_bytes = reporting.render_pdf(reporting.build_report(_rich_accepted_state()))
    text = _extract_pdf_text(pdf_bytes)
    for expected in (
        "AI-Architect Architecture Report", "ADR-001", "KB-E001", "FEAT-001", "Kafka",
    ):
        assert expected in text, expected


def test_pdf_wraps_long_component_and_finding_text_without_raising():
    state = _rich_done_state()
    state.adrs[0].decision = LONG_TEXT
    state.components[0].description = LONG_TEXT
    state.review.issues[0].finding = LONG_TEXT
    sign_off.accept_design(state)

    pdf_bytes = reporting.render_pdf(reporting.build_report(state))

    assert pdf_bytes[:5] == b"%PDF-"
    reader = PdfReader(BytesIO(pdf_bytes))
    assert len(reader.pages) >= 2


def test_pdf_renders_realistic_unicode_used_by_this_project():
    """Em dash, accented Latin, a checkmark, an arrow — the characters that
    actually show up in this project's own text. Never CJK: unrealistic
    content for this project and outside the vendored font's coverage."""
    pdf_bytes = reporting.render_pdf(reporting.build_report(_rich_accepted_state()))
    text = _extract_pdf_text(pdf_bytes)
    assert "café" in text
    assert "résumé" in text
    assert "✓" in text
    assert "→" in text


def test_alternatives_and_consequences_headings_render_before_their_bullets():
    """Regression pin: a labelled heading with no body paragraph under it
    (only a bullet list) must still print its label — see `_paragraph`."""
    pdf_bytes = reporting.render_pdf(reporting.build_report(_rich_accepted_state()))
    text = _extract_pdf_text(pdf_bytes)
    assert "Alternatives Considered" in text
    assert "Positive Consequences" in text
    assert "Negative Consequences" in text
    assert "Amazon SQS" in text


# ══════════════════════════════════════════════════════════════════════════
# 4. File I/O — atomic writes, per-run isolation, independent failure
# ══════════════════════════════════════════════════════════════════════════
def test_generate_reports_writes_both_files_findable_by_report_paths(tmp_path, monkeypatch):
    monkeypatch.setenv("AI_ARCHITECT_RUNS_DIR", str(tmp_path))
    state = _rich_accepted_state()

    result = reporting.generate_reports(state)

    assert result.ok
    md_path, pdf_path = reporting.report_paths(state.run_id)
    assert md_path == result.markdown_path
    assert pdf_path == result.pdf_path
    assert md_path.read_text(encoding="utf-8").startswith("# AI-Architect Architecture Report")
    assert pdf_path.read_bytes()[:5] == b"%PDF-"


def test_report_files_are_isolated_per_run(tmp_path, monkeypatch):
    monkeypatch.setenv("AI_ARCHITECT_RUNS_DIR", str(tmp_path))
    state_a = _rich_accepted_state()
    state_b = _rich_accepted_state()
    assert state_a.run_id != state_b.run_id

    reporting.generate_reports(state_a)
    assert reporting.report_paths(state_b.run_id) == (None, None)

    reporting.generate_reports(state_b)
    md_a, _ = reporting.report_paths(state_a.run_id)
    md_b, _ = reporting.report_paths(state_b.run_id)
    assert md_a is not None and md_b is not None and md_a != md_b


def test_regenerating_a_run_atomically_replaces_only_its_own_files(tmp_path, monkeypatch):
    monkeypatch.setenv("AI_ARCHITECT_RUNS_DIR", str(tmp_path))
    state = _rich_accepted_state()
    reporting.generate_reports(state)
    md_path, _ = reporting.report_paths(state.run_id)
    first = md_path.read_text(encoding="utf-8")

    state.waiver.note = "MAGIC_UPDATED_NOTE"
    reporting.generate_reports(state)
    second = md_path.read_text(encoding="utf-8")

    assert "MAGIC_UPDATED_NOTE" in second
    assert second != first
    assert not any(p.suffix == ".tmp" for p in md_path.parent.iterdir())


def test_generate_reports_before_acceptance_writes_nothing(tmp_path, monkeypatch):
    monkeypatch.setenv("AI_ARCHITECT_RUNS_DIR", str(tmp_path))
    state = _rich_done_state()  # DONE, not accepted

    result = reporting.generate_reports(state)

    assert not result.markdown_ok and not result.pdf_ok
    assert "ACCEPTED" in result.markdown_error
    assert reporting.report_paths(state.run_id) == (None, None)


def test_pdf_failure_leaves_markdown_intact_and_no_partial_pdf(tmp_path, monkeypatch):
    """The two formats fail INDEPENDENTLY — see the module docstring on
    partial failure. A Markdown write that succeeds is not undone by a PDF
    render that then fails, and no `.tmp` or corrupt target survives it."""
    monkeypatch.setenv("AI_ARCHITECT_RUNS_DIR", str(tmp_path))
    state = _rich_accepted_state()

    def _boom(report):
        raise RuntimeError("MAGIC_PDF_BOOM")

    monkeypatch.setattr(reporting, "render_pdf", _boom)
    result = reporting.generate_reports(state)

    assert result.markdown_ok
    assert not result.pdf_ok
    assert "MAGIC_PDF_BOOM" in result.pdf_error
    md_path, pdf_path = reporting.report_paths(state.run_id)
    assert md_path is not None
    assert pdf_path is None
    assert not any(p.suffix == ".tmp" for p in md_path.parent.iterdir())


def test_report_paths_rejects_a_path_traversal_run_id():
    with pytest.raises(reporting.ReportError):
        reporting.report_paths("../evil")


def test_report_paths_returns_none_for_an_unknown_run(tmp_path, monkeypatch):
    monkeypatch.setenv("AI_ARCHITECT_RUNS_DIR", str(tmp_path))
    assert reporting.report_paths("no-such-run") == (None, None)


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
